apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  maxmemory_policy: "{{ .Values.configmap.data.maxmemory_policy }}"
  maxmemory: "{{ .Values.configmap.data.maxmemory }}"
