apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: 25996-redis
  name: redis-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
